### ISSUE TITLE
Post Limit Order just hangs

### ISSUE THREAD

**Issue by joshharington** [luno/luno-python#13]
I am trying to use the Post Limit Order call on the API to sell BTC for ZAR. My script goes right up until trying to make the call to the Luno API using this library.

The Luno API key and secret are fine as I am pulling account balance just fine.

```
print('before call')
res = c.post_limit_order('XBTZAR', price, 'ASK', volume)
print('after call')
```

Using the above code, I only get the "before call" printed out, nothing else. No errors pop up either.

**Comment by neilgarb** [comment]
Thanks for the report, @joshharington. @adamhicks, are you able to reproduce?

**Comment by adamhicks** [comment]
I've been placing orders using the python and go libraries and I'm not able to reproduce this, you should at least get a timeout on the request (10s by default).

@joshharington Can you try putting a `try except` block around your `post_limit_order` call to check if you're getting an exception here?
Also worth checking that your variable `price` and `volume` are correct. They should be decimal strings as described here: https://www.luno.com/en/api#orders-post-order

**Comment by joshharington** [comment]
@adamhicks @neil I was trying again this morning and orders are now going through. Not sure what happened.

**Comment by joshharington** [comment]
This happened again last night where there was just no response and it hung
