### ISSUE TITLE
pip repository not up to date

### ISSUE THREAD

**Issue by gatkramp** [luno/luno-python#22]
Hello

It seems that the pip repository is still on version 0.0.4. Will you be able to update?

Alternatively, I used:
`pip install --upgrade https://github.com/luno/luno-python/archive/v0.0.7.tar.gz`
to install the latest version (Version 0.0.7) at the time of writing.

Thanks

**Comment by neilgarb** [comment]
Thanks for the ping! I've uploaded 0.0.7 to https://pypi.org/manage/project/luno-python/release/0.0.7/.
