### ISSUE TITLE
Can't seem to be able to initialise the client

### ISSUE THREAD

**Issue by cryptoknight2021** [luno/luno-python#28]
Hi I have just recently started to learn some basic python programming. I am trying to build an automated trading bot for Luno. However, I have an issue with even the first step of running the code   from luno_python.client import client

Have already installed the luno_python library via pip install luno-python

This issue doesn't happen when I tried to do the same for binance using the github codes. 

The results of the issue
Traceback (most recent call last):
  File "algo.py", line 43, in <module>
    from luno_python.client import client
ImportError: cannot import name 'client' from 'luno_python.client' (C:\Users\xxxx\anaconda3\lib\site-packages\luno_python\client.py)

**Comment by georgiolaz** [comment]
your  import name 'client' is incorrect as its all in lowercase try the below .

`from luno_python.client import Client`
