### ISSUE TITLE
Get_Candle seems to be missing

### ISSUE THREAD

**Issue by sanari1** [luno/luno-python#31]
It seems like the API function for get_candle hasn't been made yet. Is there any plans to have it added or am I missing something?

**Comment by NicholasFabio** [comment]
I am having the same issue with the client SDK. The function `get_candles` function doesn't seem to exist and then in the API docs to perform a normal get request for example :  `https://api.luno.com/api/exchange/1/candles?pair=XBTZAR&since=1640158922509&duration=300` the response is 'Unauthorized'. 

@NeilLuno @neilgarb @adamhicks any idea what the issue may be?

**Comment by YinYin-blip** [comment]
@sanari1 looks like there was a merge after you opened this issue (reference: #32) which adds `get_candles` as a function to the client

@NicholasFabio The get_candles function has been added :) make sure your client is up to date with this repo. But you have a point with the "Unauthorized" error. According to https://www.luno.com/en/developers/api#tag/Market

> Market data API calls can be accessed by anyone without authentication

When I run `python3 readonly.py` with `c = Client(api_key_id="", api_key_secret="")`: all market_data endpoints are successful until `get_candles` which returns:

> Traceback (most recent call last):
  File "/Users/admin/Downloads/luno-python/examples/readonly.py", line 31, in <module>
    res = c.get_candles(pair='XBTZAR', since=since, duration=300)
  File "/Users/admin/Downloads/luno-python/lib/python3.9/site-packages/luno_python/client.py", line 158, in get_candles
    return self.do('GET', '/api/exchange/1/candles', req=req, auth=True)
  File "/Users/admin/Downloads/luno-python/lib/python3.9/site-packages/luno_python/base_client.py", line 86, in do
    raise APIError(e['error_code'], e['error'])
luno_python.error.APIError: ('ErrAPIKeyNotFound', 'API key not found')

This seems to be an issue with either the documentation or the server that requires authentication for this endpoint. @neilgarb @adamhicks

**Comment by firenq** [comment]
Hi. I am trying get_candles for first time and got the error 'Client' object has no attribute 'get_candles'. Can anyone pls help? Thanks.

**Comment by neilgarb** [comment]
@firenq Are you using v0.0.9? I updated the client recently.

**Comment by firenq** [comment]
@neilgarb thanks it works after update. May I suggest to add an argument for ending at a timestamp or simply a default ending at the latest timestamp, instead of "since=" which is starting from a timestamp?
