### ISSUE TITLE
Package on PyPi is outdated

### ISSUE THREAD

**Issue by stone-za** [luno/luno-python#33]
The latest release for this project is 0.0.8, but the latest version on PyPi is 0.0.7.
@adamhicks or @neilgarb can you please update the package on PyPi?
I am happy to do it as well, but I obviously don't have permissions to do so on PyPi.

**Comment by neilgarb** [comment]
Done! https://pypi.org/project/luno-python/0.0.8/

**Comment by stone-za** [comment]
Thank you!
