### ISSUE TITLE
LUNO is a SCAM, don't use it

### ISSUE THREAD

**Issue by nextime** [luno/luno-python#34]
Don't use it, they STOLE your money and don't let you withdraw with escuses after escuses, when they answer at all.

**Comment by jonathanelscpt** [comment]
Luno isn't a scam.  You're probably juts an idiot.

Regards
*Jonathan Els*

**Comment by carelvwyk** [comment]
He contacts a fake Facebook profile and thinks it's the luno CEO...

https://github.com/luno/luno-php/issues/31#issuecomment-997334830

**Comment by jonathanelscpt** [comment]
Like I said, probably an idiot.  Case confirmed.

Regards
*Jonathan Els*
