### ISSUE TITLE
Luno: Difficulties adding the API_KEY_SECRET.

### ISSUE THREAD

**Issue by SoftTouchxxXL** [luno/luno-python#37]
Hello Everybody, I'm having trouble adding the Api_Key_Secret in my little python script on Jupyter. when I add it I get the following error

> Timeout value connect was 9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD, but it must be an int, 
float or None.

please advise.

**Comment by YinYin-blip** [comment]
Can you post the entire traceback of the error? Want to see what line of code is raising the error. How did you try add your id / secret?

If that is your secret/id that you posted, probably best to delete it as soon as possible.

**Comment by SoftTouchxxXL** [comment]
Good day YinYin-blip, apologies for the late reply.  It doesn't have one of those trace back error messages, its just this
> Timeout value connect was 9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD, but it must be an int,
float or None.

below the cell.

so I've done this

> api_key_secret="9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD"

> c = Client(api_key_id, api_key_secret)

the api_key_id also gave an error when I assigned it the same way I did the api_key_secret

> api_key_id="https://g3ypklx3vjdq8/api/1/ticker"

but after I added the "https://. .. ./api/1/ticker"
the error stopped and gave me this one

> Timeout value connect was 9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD, but it must be an int,
float or None.

for the api_secret_key.
lol both the keys I've added are just examples I've created.
I've also tried, instead of assigning the keys just putting them in the ....

> c = Client("g3ypklx3vjdq8", "9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD")

like this, still gave the same errors.

**Comment by SoftTouchxxXL** [comment]
I think it worked because, I have a different error now

> ('ErrInvalidCurrency', 'Invalid currency code.')

this is what I have

> from luno_python.client import Client

> pair='ETHZAR'

> c = Client(api_key_id="g3ypklx3vjdq8", api_key_secret="9oJvvYd463YtdV64_C6f4UiOl9834ysFelP90cvD")
try:
    res = c.get_ticker(pair)
    Bal=c.get_balances(pair)
    print (res)
    print(Bal)
except Exception as e:
    print (e)
    
The spaces between the 'Try & Except' are all correct in jupyter

> ('ErrInvalidCurrency', 'Invalid currency code.')

is the error that follows.

**Comment by YinYin-blip** [comment]
I can't replicate this issue. When I run:
```
c = Client(api_key_id=os.getenv('LUNO_API_KEY_ID'), api_key_secret=os.getenv('LUNO_API_KEY_SECRET'))
res = c.get_ticker(pair='ETHZAR')
print(res)
```
I get:
`{'pair': 'ETHZAR', 'timestamp': 1646836584026, 'bid': '42349.00000000', 'ask': '42400.00000000', 'last_trade': '42349.00000000', 'rolling_24_hour_volume': '1216.81941300', 'status': 'ACTIVE'}`

There is something wrong with your code.

Is the error coming from your `get_ticker` call or `get_balances`? Have you tried using print statements to try debug the issue?
`print(type(pair), len(pair), pair)` might give some insights

**Comment by SoftTouchxxXL** [comment]
It was the `get_balances`  part of the Code, I did this

> Bal=c.get_balances(pair)

> print(Bal)

> ('ErrInvalidCurrency', 'Invalid currency code.')

instead of

> Bal= c.get_balances(assets=['ETH'])

> print(Bal)

> {'balance': [{'account_id': '619', 'asset': 'ETH', 'balance': '619', 'reserved': '.916', 'unconfirmed': '6.19'}, {'account_id': '619', 'asset': 'ETH', 'balance': '6.19', 'reserved': '6.19', 'unconfirmed': '6.19'}]}
 
tomorrow, I test the `c.post_market_order` . I have a feeling I'm going to create all kinds of new interesting errors.
Thank you YinYin-blip, Your an absolute legend.
