### ISSUE TITLE
API error 401 for account related calls

### ISSUE THREAD

**Issue by byronerd** [luno/luno-python#43]
Hi, I'm having some trouble with API calls in this library that relate to account specific information like balances or placing orders. I can use calls like "get_ticker" and "markets" for example without any issues, but calls like "get_balances" and "post_limit_order" return the same unknown API error 401. I've set my API settings on my account to allow trading. Not sure if there is something I missed in the setup. I would appreciate any help. Thanks.

**Comment by adamhicks** [comment]
Hey there! Have you made sure to add your API key and secret to the client?
Here's the relevant line from the example
```
c = Client(api_key_id='key_id', api_key_secret='key_secret')
```
you'll need to populate those fields from your Luno API key, if you haven't created that yet you can do so on https://www.luno.com/wallet/security/api_keys

**Comment by adamhicks** [comment]
When you create a new API key on Luno you need to use your trusted device (phone) to authorise the API key before it can be used by code. This is an extra step to improve security of your account, did you complete this step?

**Comment by byronerd** [comment]
Yes I did.
