### ISSUE TITLE
luno trading bot

### ISSUE THREAD

**Issue by gertwillemse** [luno/luno-python#45]
C:\Users\gwill\PycharmProjects\pythonProject2\luno\venv\Scripts\python.exe C:/Users/gwill/luno.py
Traceback (most recent call last):
  File "C:\Users\gwill\luno.py", line 2, in <module>
    from luno_python.client import Client
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'luno_python'

Process finished with exit code 1

Anyone that can give advice on how to solve this issue?
Thanks in advance

**Comment by aamustapha** [comment]
first you need to be sure you've run pip install.
Second, you need to also be sure it's same context.

If you install luno_python on python2, you can't run it through python 3 and vice versa
if you install luno_python in a specific project, you might not be able to access it in another project

**Comment by echarrod** [comment]
Hi @gertwillemse, are you still having issues with this?

**Comment by echarrod** [comment]
Closing this, as it seems to be a duplicate of https://github.com/luno/luno-python/issues/44
