### ISSUE TITLE
Get a pairs full history

### ISSUE THREAD

**Issue by sanari1** [luno/luno-python#48]
Gooday

Is there a way to get the full candle history?

I'm currently doing this but doesn't seem to be working correctly. For example ETH/ZAR the start date is 2019-07-09 14:00:00 but should be 2017-08-28.

def get_history(c, Pair):
    exits=True
    stamp=3600
    since=int(int(time.time())*1000-31536032000*1*30)
    raw_data=c.get_candles(stamp,Pair,since)
    candles=pd.DataFrame(raw_data["candles"],dtype=float)  
    candles['timestamp']=pd.to_datetime(candles['timestamp'],unit= 'ms',utc=False)+pd.Timedelta(hours=3) 
    candles.to_csv("history.csv",mode='w',index=False)
    while since<int(int(time.time())) * 1000 and exits==True:
        since=int(raw_data["candles"][-1]["timestamp"]+stamp * 1000)
        if since<int(int(time.time())) * 1000-stamp * 1000:
            raw_data.clear()
            del candles
            raw_data=c.get_candles(stamp,Pair,since)
            candles=pd.DataFrame(raw_data["candles"],dtype=float)
            candles['timestamp']=pd.to_datetime(candles['timestamp'],unit= 'ms')
            candles.to_csv("history.csv",mode='a',index=False,header=False)
        else:
            exits=False
    return 0

Regards

**Comment by echarrod** [comment]
Hi @sanari1, thanks for raising this.

Unfortunately our data for the candle history for the ETHZAR pair only goes back to 2019. You can see this looks similar to the candle start date on https://www.luno.com/trade/markets/ETHZAR
