### ISSUE TITLE
OpenAPI spec: Type error

### ISSUE THREAD

**Issue by ff137** [luno/luno-python#54]
Good day, Luno devs! :wave:

I've generated an openapi client from the Luno spec: https://github.com/ff137/luno_openapi :rocket:

I'm writing some tests, and notice the spec is faulty! 🙅 

For example, `Ticker.timestamp` is promised to be a String, and in the response we get an int! 🙉 

This is simple to fix in post, but I'm wondering how I can contribute to correct it at the source? 👷 

If not, what is the preferred channel to report any more bugs? 🐛

Cheers! 🍻

**Comment by echarrod** [comment]
Hi @ff137, 

Thanks so much for raising this, this is the right place to raise issues 👍 

You're correct, this isn't right. We're looking into updating it now.

Going forwards we're going to try to create a CONTRIBUTING.md file too, to make it clear how to contribute, if anyone outside of Luno would like to. 

We use https://github.com/luno/sdkgen to generate parts of our SDKs, which we also want to add some documentation to 🙂 

We'll update here once we've updated the SDK 👍

**Comment by ff137** [comment]
Awesome, thanks so much for the feedback!

I'll take a look at the sdkgen - might give me some motivation to finally learn go, which would be good.

I look forward to making some more contributions if and when I can, as I get chance to work more with the API.

(PS: reading again, not sure what possessed me to end every line with an emoji, but it came naturally 😂)

We can prob close the issue. Or if you'll please let me know when the new OpenAPI spec is published, then I can regenerate the client and check it out.

Thanks!

**Comment by echarrod** [comment]
Hi @ff137, we appreciated the emojis 😁 

We've regenerated the Python SDK after updating the spec - https://github.com/luno/luno-python/pull/55

Can you confirm from your side this looks as expected now?

Thanks

**Comment by ff137** [comment]
Thank you! @echarrod 
Will confirm as soon as I get chance

**Comment by ff137** [comment]
Good news! I can confirm that the timestamp TypeError has been resolved across the board: https://github.com/ff137/luno_openapi/pull/2/commits/6819794fcf38d81ee3c333367bbc658530af3a1d
Thanks @echarrod 👏 enjoy the day! 😄
